"""
app/services/pdf_generator.py
-----------------------------
Generate a professional PDF health report using ReportLab.
Clean, readable, WhatsApp-shareable format.
"""
from reportlab.lib.pagesizes import A4
from reportlab.lib import colors
from reportlab.lib.units import mm
from reportlab.lib.styles import getSampleStyleSheet, ParagraphStyle
from reportlab.platypus import (
    SimpleDocTemplate, Paragraph, Spacer, Table, TableStyle, HRFlowable
)
from reportlab.graphics.shapes import Drawing, Rect, Circle, String
from reportlab.graphics.charts.barcharts import VerticalBarChart
from reportlab.graphics.charts.legends import Legend
from reportlab.graphics.widgets.markers import makeMarker
from reportlab.pdfbase import pdfmetrics
from reportlab.pdfbase.ttfonts import TTFont
import io
import os
import re
import html
from datetime import datetime

# Attempt to load a Unicode-compliant system font for foreign languages (Indic, CJK, etc.)
# Fallback to Helvetica if not found.
FONT_REGULAR = "Helvetica"
FONT_BOLD = "Helvetica-Bold"
FONT_OBLIQUE = "Helvetica-Oblique"

def _register_unicode_fonts():
    global FONT_REGULAR, FONT_BOLD
    font_paths = [
        "C:\\Windows\\Fonts\\Nirmala.ttc",
        "C:\\Windows\\Fonts\\Nirmala.ttf",
        "/usr/share/fonts/truetype/noto/NotoSans-Regular.ttf", # Linux fallback
    ]
    
    for path in font_paths:
        if os.path.exists(path):
            try:
                if path.endswith(".ttc"):
                    # TTC (TrueType Collection) usually contains multiple faces.
                    # Index 0 is usually Regular, Index 1 is usually Bold for Nirmala.
                    pdfmetrics.registerFont(TTFont("Nirmala", path, subfontIndex=0))
                    pdfmetrics.registerFont(TTFont("Nirmala-Bold", path, subfontIndex=1))
                    FONT_REGULAR = "Nirmala"
                    FONT_BOLD = "Nirmala-Bold"
                    return True
                else:
                    pdfmetrics.registerFont(TTFont("Unicode-Regular", path))
                    FONT_REGULAR = "Unicode-Regular"
                    # Try to find a bold companion if it's a TTF
                    bold_path = path.replace("Regular", "Bold").replace(".ttf", "b.ttf")
                    if os.path.exists(bold_path):
                        pdfmetrics.registerFont(TTFont("Unicode-Bold", bold_path))
                        FONT_BOLD = "Unicode-Bold"
                    return True
            except Exception as e:
                print(f"Warning: Failed to load font at {path}: {e}")
    return False

_register_unicode_fonts()

# ── Color Palette ─────────────────────────────────────────────────────────────
C_DARK      = colors.HexColor("#0e1522")
C_ACCENT    = colors.HexColor("#2563eb") # Darker blue for light theme
C_GREEN     = colors.HexColor("#10b981") # Richer green
C_WARN      = colors.HexColor("#f59e0b") # Richer amber
C_DANGER    = colors.HexColor("#ef4444") # Richer red
C_LIGHT     = colors.HexColor("#1e293b") # TEXT COLOR: Changed to dark slate for light backgrounds
C_MUTED     = colors.HexColor("#64748b") # Darker slate for muted text
C_WHITE     = colors.white
C_STATUS    = {"High": C_DANGER, "Low": colors.HexColor("#0f172a"), "Normal": C_GREEN} # Red, Black, Green as requested
C_ALERT     = {"CRITICAL": C_DANGER, "HIGH": C_WARN, "ELEVATED": C_ACCENT, "NORMAL": C_GREEN}
 
# ── Multilingual Lookups ──────────────────────────────────────────────────────
TRANSLATIONS = {
    "English": {
        "title": "MediLens AI", "subtitle": "Grounded Medical Report Intelligence", "generated": "Generated",
        "profile": "Patient Profile", "name": "Name", "age": "Age", "gender": "Gender", "language": "Language", "mode": "Report Mode",
        "alert_title": "Overall Health Alert", "alert_level": "Alert Level", "confidence": "AI Confidence Score",
        "summary": "Executive Summary", "lab_results": "Lab Test Results", "test": "Test", "value": "Value", "range": "Range Visual", "status": "Status",
        "trend_title": "Comparative Trend (vs Previous Report)", "change": "Change", "abnormalities": "Priority Abnormalities Detailed",
        "explanation": "AI Health Explanation", "disclaimer": "Medical Disclaimer", "comparative": "Comparative Analysis: Previous vs Current Report",
        "privacy": "Privacy: No patient data is stored. All processing is in-session only.",
        "final_disclaimer": "DISCLAIMER: This report is generated by an AI system for informational and educational purposes only. It does NOT constitute a medical diagnosis, medical advice, or a substitute for professional medical consultation. Always consult a qualified healthcare professional."
    },
    "Hindi": {
        "title": "MediLens AI", "subtitle": "ग्राउंडेड मेडिकल रिपोर्ट इंटेलिजेंस", "generated": "उत्पन्न",
        "profile": "रोगी का विवरण", "name": "नाम", "age": "आयु", "gender": "लिंग", "language": "भाषा", "mode": "रिपोर्ट मोड",
        "alert_title": "समग्र स्वास्थ्य अलर्ट", "alert_level": "अलर्ट स्तर", "confidence": "AI आत्मविश्वास स्कोर",
        "summary": "कार्यकारी सारांश", "lab_results": "लैब टेस्ट परिणाम", "test": "टेस्ट", "value": "मूल्य", "range": "रेंज विजुअल", "status": "स्थिति",
        "trend_title": "तुलनात्मक रुझान (पिछले रिपोर्ट के मुकाबले)", "change": "परिवर्तन", "abnormalities": "प्राथमिकता असामान्यता विवरण",
        "explanation": "AI स्वास्थ्य स्पष्टीकरण", "disclaimer": "चिकित्सा अस्वीकरण", "comparative": "तुलनात्मक विश्लेषण: पिछले बनाम वर्तमान रिपोर्ट",
        "privacy": "गोपनीयता: कोई रोगी डेटा संग्रहीत नहीं किया जाता है।",
        "final_disclaimer": "अस्वीकरण: यह रिपोर्ट केवल सूचनात्मक और शैक्षिक उद्देश्यों के लिए AI सिस्टम द्वारा तैयार की गई है।"
    },
    "Tamil": {
        "title": "MediLens AI", "subtitle": "மருத்துவ அறிக்கை நுண்ணறிவு", "generated": "உருவாக்கப்பட்டது",
        "profile": "நோயாளி சுயவிவரம்", "name": "பெயர்", "age": "வயது", "gender": "பாலினம்", "language": "மொழி", "mode": "அறிக்கை முறை",
        "alert_title": "ஒட்டுமொத்த சுகாதார எச்சரிக்கை", "alert_level": "எச்சரிக்கை நிலை", "confidence": "AI தன்னம்பிக்கை மதிப்பெண்",
        "summary": "நிர்வாக சுருக்கம்", "lab_results": "ஆய்வக சோதனை முடிவுகள்", "test": "சோதனை", "value": "மதிப்பு", "range": "வரம்பு காட்சி", "status": "நிலை",
        "trend_title": "ஒப்பீட்டு போக்கு (முந்தைய அறிக்கையுடன்)", "change": "மாற்றம்", "abnormalities": "முன்னுரிமை அசாதாரணமான விரிவான விவரங்கள்",
        "explanation": "AI சுகாதார விளக்கம்", "disclaimer": "மருத்துவ மறுப்பு", "comparative": "ஒப்பீட்டு பகுப்பாய்வு: முந்தைய vs தற்போதைய அறிக்கை",
        "privacy": "தனியுரிமை: நோயாளி தரவு எதுவும் சேமிக்கப்படவில்லை.",
        "final_disclaimer": "மறுப்பு: இந்த அறிக்கை தகவல் மற்றும் கல்வி நோக்கங்களுக்காக AI அமைப்பால் உருவாக்கப்பட்டது."
    },
    "Telugu": {
        "title": "MediLens AI", "subtitle": "వైద్య నివేదిక మేధస్సు", "generated": "సృష్టించబడింది",
        "profile": "రోగి ప్రొఫైల్", "name": "పేరు", "age": "వయస్సు", "gender": "లింగం", "language": "భాష", "mode": "నివేదిక మోడ్",
        "alert_title": "మొత్తం ఆరోగ్య హెచ్చరిక", "alert_level": "హెచ్చరిక స్థాయి", "confidence": "AI విశ్వాస స్కోరు",
        "summary": "కార్యనిర్వాహక సారాంశం", "lab_results": "ల్యాబ్ పరీక్ష ఫలితాలు", "test": "పరీక్ష", "value": "విలువ", "range": "శ్రేణి విజువల్", "status": "స్థితి",
        "trend_title": "తులనాత్మక ధోరణి (మునుపటి నివేదికతో)", "change": "మార్పు", "abnormalities": "ప్రాధాన్యత అసాధారణతల వివరాలు",
        "explanation": "AI ఆరోగ్య వివరణ", "disclaimer": "వైద్య నిరాకరణ", "comparative": "తులనాత్మక విశ్లేషణ: మునుపటి vs ప్రస్తుత నివేదిక",
        "privacy": "గోప్యత: రోగి డేటా ఏదీ నిల్వ చేయబడదు.",
        "final_disclaimer": "నిరాకరణ: ఈ నివేదిక కేవలం సమాచారం మరియు విద్యా ప్రయోజనాల కోసం AI ద్వారా రూపొందించబడింది."
    },
    "Spanish": {
        "title": "MediLens AI", "subtitle": "Inteligencia de Informes Médicos", "generated": "Generado",
        "profile": "Perfil del Paciente", "name": "Nombre", "age": "Edad", "gender": "Género", "language": "Idioma", "mode": "Modo de Informe",
        "alert_title": "Alerta de Salud General", "alert_level": "Nivel de Alerta", "confidence": "Puntaje de Confianza AI",
        "summary": "Resumen Ejecutivo", "lab_results": "Resultados de Laboratorio", "test": "Prueba", "value": "Valor", "range": "Visual de Rango", "status": "Estado",
        "trend_title": "Tendencia Comparativa (vs Informe Anterior)", "change": "Cambio", "abnormalities": "Detalle de Anormalidades Prioritarias",
        "explanation": "Explicación de Salud AI", "disclaimer": "Aviso Médico", "comparative": "Análisis Comparativo: Informe Anterior vs Actual",
        "privacy": "Privacidad: No se almacenan datos del paciente.",
        "final_disclaimer": "AVISO: Este informe es generado por un sistema de IA con fines informativos y educativos únicamente."
    }
}


def _create_sparkline(val: float, min_val: float, max_val: float, width=50, height=8) -> Drawing:
    """Draw a minimalist reference range sparkline."""
    d = Drawing(width, height)
    
    # Background total span (light gray)
    d.add(Rect(0, height/2 - 1.5, width, 3, fillColor=colors.HexColor("#e2e8f0"), strokeColor=None, rx=1.5, ry=1.5))
    
    range_span = max_val - min_val
    if range_span <= 0:
        return d
    
    # Calculate dot position (bounded between 0 and 1)
    pct = (val - min_val) / range_span
    
    # Safe zone (darker gray)
    safe_width = width * 0.4 # arbitrarily visually centralize the safe 40% of the bar
    safe_x = width/2 - safe_width/2
    d.add(Rect(safe_x, height/2 - 1.5, safe_width, 3, fillColor=colors.HexColor("#94a3b8"), strokeColor=None, rx=1.5, ry=1.5))

    # Dot positioning
    dot_x = 0
    dot_color = C_GREEN

    if pct < 0:
        dot_x = max(0, safe_x - 5)
        dot_color = C_STATUS["Low"]
    elif pct > 1:
        dot_x = min(width, safe_x + safe_width + 5)
        dot_color = C_STATUS["High"]
    else:
        # Interpolate within the safe zone
        dot_x = safe_x + (pct * safe_width)
        dot_color = C_GREEN
        
    d.add(Circle(dot_x, height/2, 3.5, fillColor=dot_color, strokeColor=colors.white, strokeWidth=1))
    return d

def _level_color(level: str) -> colors.Color:
    return C_ALERT.get(level.upper(), C_MUTED)


def generate_health_pdf(data: dict) -> bytes:
    """
    Generate and return a PDF health report as bytes.

    Parameters
    ----------
    data : dict — result from the /analyze endpoint
    """
    buffer = io.BytesIO()
    doc = SimpleDocTemplate(
        buffer, pagesize=A4,
        topMargin=20*mm, bottomMargin=20*mm,
        leftMargin=18*mm, rightMargin=18*mm,
    )

    styles  = getSampleStyleSheet()
    W       = A4[0] - 36*mm  # usable width

    # ── Custom Styles ──────────────────────────────────────────────────────────
    h1 = ParagraphStyle("H1", parent=styles["Heading1"],
                         fontSize=20, textColor=C_ACCENT,
                         spaceAfter=4, fontName=FONT_BOLD)
    h2 = ParagraphStyle("H2", parent=styles["Heading2"],
                         fontSize=13, textColor=C_LIGHT,
                         spaceAfter=3, fontName=FONT_BOLD)
    h3 = ParagraphStyle("H3", parent=styles["Heading3"],
                         fontSize=10, textColor=C_MUTED,
                         spaceAfter=2, fontName=FONT_BOLD,
                         textTransform="uppercase", letterSpacing=1)
    body = ParagraphStyle("Body", parent=styles["Normal"],
                           fontSize=10, textColor=C_LIGHT,
                           spaceAfter=6, leading=15, fontName=FONT_REGULAR)
    small = ParagraphStyle("Small", parent=styles["Normal"],
                            fontSize=8.5, textColor=C_MUTED,
                            spaceAfter=4, leading=12, fontName=FONT_REGULAR)
    disclaimer = ParagraphStyle("Disc", parent=styles["Normal"],
                                 fontSize=8, textColor=C_MUTED,
                                 spaceAfter=4, leading=11,
                                 fontName=FONT_OBLIQUE)

    story = []

    lang   = data.get("language", "English")
    T = TRANSLATIONS.get(lang, TRANSLATIONS["English"])

    # ── Header ──────────────────────────────────────────────────────────────────
    story.append(Paragraph(T["title"], h1))
    story.append(Paragraph(T["subtitle"], small))
    story.append(Paragraph(f"{T['generated']}: {datetime.now().strftime('%d %B %Y, %I:%M %p')}", small))
    story.append(HRFlowable(width="100%", thickness=1, color=C_ACCENT, spaceAfter=10))

    # ── Patient Info ─────────────────────────────────────────────────────────────
    story.append(Paragraph(T["profile"], h2))
    name   = data.get("patient_name") or "—"
    age    = data.get("patient_age", "—")
    gender = data.get("patient_gender", "—")
    mode   = data.get("mode", "patient").title()

    # Show patient name prominently if available
    if name and name != "—":
        name_style = ParagraphStyle("Name", parent=styles["Normal"],
                                     fontSize=15, textColor=C_DARK,
                                     spaceAfter=4, fontName=FONT_BOLD)
        story.append(Paragraph(name, name_style))

    patient_data = [
        [T["name"], name, T["age"], str(age)],
        [T["gender"], gender, T["language"], lang],
        [T["mode"], mode, "", ""],
    ]
    pt = Table(patient_data, colWidths=[W*0.2, W*0.3, W*0.2, W*0.3])
    pt.setStyle(TableStyle([
        ("FONTNAME",    (0,0), (-1,-1), FONT_REGULAR),
        ("FONTSIZE",    (0,0), (-1,-1), 10),
        ("TEXTCOLOR",  (0,0), (0,-1), C_MUTED),
        ("TEXTCOLOR",  (2,0), (2,-1), C_MUTED),
        ("TEXTCOLOR",  (1,0), (1,-1), C_LIGHT),
        ("TEXTCOLOR",  (3,0), (3,-1), C_LIGHT),
        ("BOTTOMPADDING", (0,0), (-1,-1), 6),
    ]))
    story.append(pt)
    story.append(Spacer(1, 8))

    # ── Overall Status ───────────────────────────────────────────────────────────
    alert  = data.get("alert", {})
    level  = alert.get("alert_level", "NORMAL")
    emoji  = {"CRITICAL": "🔴", "HIGH": "🟡", "ELEVATED": "🟡", "NORMAL": "🟢"}.get(level, "⚪")
    story.append(Paragraph(T["alert_title"], h2))
    story.append(Paragraph(f"{emoji} {T['alert_level']}: <b>{level}</b>", body))
    story.append(Paragraph(alert.get("trigger_reason", ""), small))

    conf = data.get("confidence", {})
    story.append(Paragraph(f"{T['confidence']}: <b>{conf.get('percentage', 'N/A')}</b>", body))
    story.append(Spacer(1, 6))

    # ── Executive Summary Extraction ──────────────────────────────────────────────
    explanation = data.get("explanation", "")
    executive_summary = None
    
    # Try to extract the summary block generated by the LLM prompt
    match = re.search(r'\[EXECUTIVE_SUMMARY\](.*?)\[/EXECUTIVE_SUMMARY\]', explanation, re.DOTALL | re.IGNORECASE)
    if match:
        executive_summary = match.group(1).strip()
        # Remove it from the main explanation so it doesn't print twice
        explanation = re.sub(r'\[EXECUTIVE_SUMMARY\].*?\[/EXECUTIVE_SUMMARY\]', '', explanation, flags=re.DOTALL | re.IGNORECASE).strip()
    elif not explanation:
        # Fallback if no explanation exists
        executive_summary = "Pending detailed AI analysis."

    if executive_summary:
        story.append(Paragraph(T["summary"], h2))
        
        # Clean markdown bolding
        safe_summary = html.escape(executive_summary)
        formatted_summary = re.sub(r'\*\*(.*?)\*\*', r'<b>\1</b>', safe_summary)
        formatted_summary = formatted_summary.replace('\n', '<br/>')
        
        # Draw inside a highlighted box
        summary_t = Table([[Paragraph(formatted_summary, body)]], colWidths=[W])
        summary_t.setStyle(TableStyle([
            ("BACKGROUND",  (0,0), (-1,-1), colors.HexColor("#e0f2fe")), # soft blue background
            ("TOPPADDING",  (0,0), (-1,-1), 8),
            ("BOTTOMPADDING",(0,0),(-1,-1), 8),
            ("LEFTPADDING", (0,0), (-1,-1), 10),
            ("RIGHTPADDING",(0,0),(-1,-1), 10),
            ("ROUNDEDCORNERS", [3, 3, 3, 3]),
        ]))
        story.append(summary_t)
        story.append(Spacer(1, 10))


    # ── Lab Results Table (Grouped by Medical Domain) ─────────────────────────────────
    story.append(HRFlowable(width="100%", thickness=0.5, color=C_MUTED, spaceAfter=8))
    story.append(Paragraph(T["lab_results"], h2))

    tests = data.get("tests", {})
    if tests:
        # Determine unique domains, defaulting to "General" if not provided
        domains = {}
        for name, d in tests.items():
            domain = d.get("domain", "General Overview")
            if domain not in domains:
                domains[domain] = {}
            domains[domain][name] = d

        for domain, domain_tests in domains.items():
            story.append(Paragraph(f"<b>{domain}</b>", h3))
            
            header = [
                Paragraph(f"<b>{T['test']}</b>", ParagraphStyle("TH", parent=body, textColor=C_MUTED, fontSize=9)),
                Paragraph(f"<b>{T['value']}</b>", ParagraphStyle("TH", parent=body, textColor=C_MUTED, fontSize=9)),
                Paragraph(f"<b>{T['range']}</b>", ParagraphStyle("TH", parent=body, textColor=C_MUTED, fontSize=9)),
                Paragraph(f"<b>{T['status']}</b>", ParagraphStyle("TH", parent=body, textColor=C_MUTED, fontSize=9)),
            ]
            rows = [header]
            for name, d in domain_tests.items():
                status = d.get("status", "Normal")
                sc = C_STATUS.get(status, C_LIGHT)
                
                # Try generating Sparkline
                visual = ""
                raw_val = str(d.get("value", ""))
                try:
                    num_val = float(raw_val)
                    ref_str = str(d.get("reference_range", ""))
                    match = re.search(r'(\d+\.?\d*)\s*[-–]\s*(\d+\.?\d*)', ref_str)
                    if match:
                        visual = _create_sparkline(num_val, float(match.group(1)), float(match.group(2)))
                    else:
                        visual = Paragraph("—", body)
                except ValueError:
                    visual = Paragraph("—", body)

                
                # Pill Badge formatting hack using ReportLab background colors
                bg_color = "eef2ff" if status == "Normal" else ("fef2f2" if status == "High" else "f8fafc")
                text_color = sc.hexval()[2:]
                badge = f"""<font color='#{text_color}'><b> {status.upper()} </b></font>"""
                
                value_text = f"{raw_val} <font size='7.5' color='#64748b'>{d.get('unit', '')}</font>"

                rows.append([
                    Paragraph(name, body),
                    Paragraph(value_text, body),
                    visual,
                    Paragraph(badge, body),
                ])
                
            t = Table(rows, colWidths=[W*0.40, W*0.20, W*0.20, W*0.20])
            t.setStyle(TableStyle([
                ("BACKGROUND",  (0,0), (-1,0), colors.HexColor("#f1f5f9")),
                ("ROWBACKGROUNDS",(0,1),(-1,-1),[colors.HexColor("#ffffff"), colors.HexColor("#f8fafc")]),
                ("GRID",        (0,0), (-1,-1), 0.5, colors.HexColor("#cbd5e1")),
                ("FONTNAME",    (0,0), (-1,-1), FONT_REGULAR),
                ("FONTSIZE",    (0,0), (-1,-1), 10),
                ("TOPPADDING",  (0,0), (-1,-1), 6),
                ("BOTTOMPADDING",(0,0),(-1,-1), 6),
                ("VALIGN",      (0,0), (-1,-1), "MIDDLE"),
            ]))
            story.append(t)
            story.append(Spacer(1, 10))

    # ── Trend ────────────────────────────────────────────────────────────────────
    trend = data.get("trend")
    if trend and trend.get("trends"):
        story.append(HRFlowable(width="100%", thickness=0.5, color=C_MUTED, spaceAfter=8))
        story.append(Paragraph(T["trend_title"], h2))
        thead = [[T["test"],T["profile"] if lang=="English" else "Prev",T["value"] if lang=="English" else "Curr",T["change"],T["status"]]]
        trows = []
        for t_item in trend["trends"]:
            pct  = t_item.get("change_pct")
            sign = ("+" if pct and pct > 0 else "") if pct is not None else ""
            pct_str = f"{sign}{pct}%" if pct is not None else "—"
            arrow = "↑" if (pct and pct > 0) else ("↓" if (pct and pct < 0) else "→")
            trows.append([
                t_item["test"],
                f"{t_item['previous_value']} {t_item['unit']}",
                f"{t_item['current_value']} {t_item['unit']}",
                f"{arrow} {pct_str}",
                t_item["current_status"],
            ])
        tr = Table(thead + trows, colWidths=[W*0.28, W*0.18, W*0.18, W*0.18, W*0.18])
        tr.setStyle(TableStyle([
            ("BACKGROUND",  (0,0), (-1,0), colors.HexColor("#f1f5f9")),
            ("GRID",        (0,0), (-1,-1), 0.5, colors.HexColor("#cbd5e1")),
            ("FONTNAME",    (0,0), (-1,-1), FONT_REGULAR),
            ("FONTSIZE",    (0,0), (-1,-1), 9),
            ("TOPPADDING",  (0,0), (-1,-1), 5),
            ("BOTTOMPADDING",(0,0),(-1,-1), 5),
        ]))
        story.append(tr)
        story.append(Spacer(1, 10))

    # ── Priority Abnormalities Detailed ───────────────────────────────────────────
    priority_list = data.get("priority_list", [])
    if priority_list:
        story.append(HRFlowable(width="100%", thickness=0.5, color=C_MUTED, spaceAfter=8))
        story.append(Paragraph(T["abnormalities"], h2))
        for p in priority_list:
            status     = p.get("status", "Unknown")
            parameter  = p.get("parameter", "Unknown")
            reason     = p.get("reason", "")
            
            sc = C_STATUS.get(status, C_DANGER) if status in C_STATUS else C_DANGER
            story.append(Paragraph(
                f"<font color='#{sc.hexval()[2:]}'>● {status}</font> <b>{parameter}</b>", 
                body
            ))
            if reason:
                story.append(Paragraph(reason, small))
        story.append(Spacer(1, 10))

    # ── AI Explanation ────────────────────────────────────────────────────────────
    # The 'explanation' variable was already extracted and cleaned of the Executive Summary above
    if explanation:
        story.append(HRFlowable(width="100%", thickness=0.5, color=C_MUTED, spaceAfter=8))
        story.append(Paragraph(T["explanation"], h2))
        
        paragraphs = explanation.split('\n\n')
        for para in paragraphs:
            para = para.strip()
            if para:
                # IMPORTANT: Escape LLM output so '<' and '&' don't crash ReportLab XML parser
                safe_para = html.escape(para)
                
                # Check if this paragraph is completely wrapped in **bolds** (meaning it's a section header)
                # Ensure it doesn't contain a bullet point or long text. Just a short line title.
                is_header = False
                if safe_para.startswith('**') and safe_para.endswith('**') and len(safe_para) < 100 and '\n' not in safe_para:
                    is_header = True
                    # Strip the ** tokens for the header style
                    clean_text = safe_para[2:-2].strip()
                    story.append(Spacer(1, 6)) # Extra visual padding before headers
                    story.append(Paragraph(clean_text, h3))
                else:
                    # Regular body paragraph: cleanly convert inline markdown **bold** to ReportLab <b>bold</b>
                    formatted_para = re.sub(r'\*\*(.*?)\*\*', r'<b>\1</b>', safe_para)
                    # Apply <br/> to handle single newlines inside blocks
                    formatted_para = formatted_para.replace('\n', '<br/>')
                    story.append(Paragraph(formatted_para, body))
                
                story.append(Spacer(1, 4))
        
        story.append(Spacer(1, 15))
        story.append(Paragraph(
            f"<font color='#64748b'><b>{T['disclaimer']}:</b><br/>"
            f"{T['final_disclaimer']}</font>",
            small
        ))

    # ── Comparative Bar Chart (only when 2 reports are compared) ─────────────────
    trend = data.get("trend")
    if trend and trend.get("trends"):
        trend_items = [
            t for t in trend["trends"]
            if t.get("previous_value") is not None and t.get("current_value") is not None
        ]
        # Cap at 12 parameters for readability
        trend_items = trend_items[:12]

        if trend_items:
            story.append(HRFlowable(width="100%", thickness=0.5, color=C_MUTED, spaceAfter=8))
            story.append(Paragraph(T["comparative"], h2))
            story.append(Paragraph(
                "The chart below compares lab values between your previous report (blue) and current report (orange).",
                small
            ))
            story.append(Spacer(1, 6))

            labels   = [t["test"][:18] for t in trend_items]   # truncate long names
            prev_vals = [float(t["previous_value"]) for t in trend_items]
            curr_vals = [float(t["current_value"])  for t in trend_items]

            n = len(labels)
            chart_w = W
            chart_h = 180
            draw_h  = chart_h + 50   # extra space for x-labels + legend

            d = Drawing(chart_w, draw_h)

            bc = VerticalBarChart()
            bc.x        = 30
            bc.y        = 40
            bc.width    = chart_w - 50
            bc.height   = chart_h - 40
            bc.data     = [prev_vals, curr_vals]
            bc.bars[0].fillColor = colors.HexColor("#3b82f6")    # Previous – blue
            bc.bars[1].fillColor = colors.HexColor("#f97316")    # Current  – orange
            bc.bars[0].strokeColor = None
            bc.bars[1].strokeColor = None

            bc.categoryAxis.categoryNames    = labels
            bc.categoryAxis.labels.angle     = 35 if n > 6 else 0
            bc.categoryAxis.labels.fontName  = FONT_REGULAR
            bc.categoryAxis.labels.fontSize  = 7.5
            bc.categoryAxis.labels.boxAnchor = "ne" if n > 6 else "n"
            bc.categoryAxis.labels.dy        = -4
            bc.categoryAxis.strokeColor      = colors.HexColor("#cbd5e1")

            bc.valueAxis.labels.fontName  = FONT_REGULAR
            bc.valueAxis.labels.fontSize  = 8
            bc.valueAxis.strokeColor      = colors.HexColor("#cbd5e1")
            bc.valueAxis.gridStrokeColor  = colors.HexColor("#f1f5f9")
            bc.valueAxis.visibleGrid      = True

            bc.groupSpacing = 5
            bc.barSpacing   = 1

            # Legend
            legend = Legend()
            legend.x             = bc.x
            legend.y             = draw_h - 12
            legend.fontName      = FONT_REGULAR
            legend.fontSize      = 8
            legend.columnMaximum = 1
            legend.deltax        = 75
            legend.deltay        = 0
            legend.dx            = 10
            legend.dy            = 6
            legend.autoXPadding  = 5
            legend.colorNamePairs = [
                (colors.HexColor("#3b82f6"), "Previous Report"),
                (colors.HexColor("#f97316"), "Current Report"),
            ]

            d.add(bc)
            d.add(legend)
            story.append(d)
            story.append(Spacer(1, 10))

    story.append(Spacer(1, 8))

    # ── Privacy & Disclaimer ──────────────────────────────────────────────────────
    story.append(HRFlowable(width="100%", thickness=0.5, color=C_MUTED, spaceAfter=6))
    story.append(Paragraph(f"🔒 {T['privacy']}", small))
    story.append(Paragraph(f"⚠️ {T['final_disclaimer']}", disclaimer))

    doc.build(story)
    return buffer.getvalue()
